#!/bin/bash

# ==== Utility functions ====

escape()
{
echo "$1"| sed -e "s/ /\\\\\\ /g"
}

# ==== Module functions ====

check(){
	if ! ( which oggdec > /dev/null 2>&1 ); then
		cat <<EOF
   FATAL: Can't find 'oggdec' binary!
   
          Please install 'vorbis-tools' package using software manager
          of your linux distributive.
EOF
		exit 1
	fi
	if ! ( which sox > /dev/null 2>&1 ); then
		cat <<EOF
   FATAL: Can't find 'sox' binary!
   
          Please install 'sox' package using software manager of 
          your linux distributive.
EOF
		exit 1
	fi
}

format(){
	# sound files are always rendered to wav format
	echo "wav"
}

deps(){
	echo
}

rules(){
	TEMPFILE=$RENDERPATH.$$
	echo "`escape "$RENDERPATH"`: `escape "$TARGET"` $DEPS" >> "$MAKEFILE"
	cat >> "$MAKEFILE" << EOF
	rm -rf "$RENDERPATH"
	oggdec "$TARGET" -o "$TEMPFILE"
	sox "$TEMPFILE" "$RENDERPATH" rate -v $AUDIO_RATE
	rm -rf "$TEMPFILE"
EOF

	echo "`escape "$RENDERPATH-clean:"`" >> "$MAKEFILE"
	echo "	rm -rf \"$RENDERPATH\"" >> "$MAKEFILE"
	echo "	rm -rf \"$TEMPFILE\"" >> "$MAKEFILE"
}

$1 "$2"
