#!/bin/bash

set -e

SCRIPT_PATH=$(cd `dirname $0`; pwd)

cd $SCRIPT_PATH

BINARY_FILES="remake remake-gui remake-manager"
LIB_FILES=`find modules`
DATA_FILES=`find project tests -path 'project/render*' -prune -o -path 'project/packs*' -prune -o -print`
DOC_FILES="LICENSE README"

PREFIX="/usr/local"

if [ ! -z "$1" ]; then
	if [[ "$1" == "--help" ]]; then
		echo "Usage: $0 [prefix]"
		echo
		echo "Default prefix: /usr/local"
		exit 0
	else
		PREFIX="$1"
	fi
fi

echo
echo "Installing Remake to $PREFIX ..."

OLD_IFS=$IFS      # save the field separator    
IFS=$' \n'     # new field separator, the end of line    

for FILE in $BINARY_FILES
do
	COMMAND="install -D -m 755 $FILE ${PREFIX}/bin/$FILE"
	[ -d $FILE ] || ( echo $COMMAND && $COMMAND )
done

for FILE in $LIB_FILES
do
	COMMAND="install -D -m 644 $FILE ${PREFIX}/lib/remake/$FILE"
	[ -d $FILE ] || ( echo $COMMAND && $COMMAND )
done

for FILE in $DATA_FILES
do
	COMMAND="install -D -m 644 $FILE ${PREFIX}/share/remake/$FILE"
	[ -d $FILE ] || ( echo $COMMAND && $COMMAND )
done

for FILE in $DOC_FILES
do
	COMMAND="install -D -m 644 $FILE ${PREFIX}/share/doc/remake/$FILE"
	[ -d $FILE ] || ( echo $COMMAND && $COMMAND )
done

# Desktop data
COMMAND="install -D -m 644 remake.desktop ${PREFIX}/share/applications/remake.desktop"
echo $COMMAND && $COMMAND
update-desktop-database || true
# Nautilus-actions 3.0
for FILE in `ls -1 desktop/nautilus-actions-3/`
do
	COMMAND="install -D -m 644 desktop/nautilus-actions-3/$FILE ${PREFIX}/share/file-manager/actions/$FILE"
	[ -d $FILE ] || ( echo $COMMAND && $COMMAND )
done
# KDE Dolphin/Konqueror actions
if [ -z "$KDE_SERVICES_PREFIX" ]; then
	export KDE_SERVICES_PREFIX="/usr/share/kde4/services/ServiceMenus"
fi
COMMAND="install -D -m 644 desktop/kde-actions/remake.desktop ${KDE_SERVICES_PREFIX}/remake.desktop"
echo $COMMAND && $COMMAND


IFS=$OLD_IFS     # restore default field separator

echo "Done."
